### ISSUE TITLE
 No such file or directory 'af3_batch_.json'

### ISSUE THREAD

**Issue by IlyesAbdelhamid** [GBLille/MassiveFold#12]
Hello,

After having installed MassiveFold successfully, I ran the following example command from your README : 
./run_massivefold.sh -s input/H1140.fasta -r af3_default_run -p 5 -f AlphaFold3_params.json -t AlphaFold3

The alignment is fine but jobarray log contains the following error: 

output_path is /data/horse/ws/iabdelha-AF3-workspace/MassiveFold/massivefold_runs/output/H1140/af3_default_run/
Fri Dec 13 08:17:35 PM CET 2024
run_alphafold.py
  --norun_data_pipeline
  --max_template_date 2024-11-28
  --json_path /data/horse/ws/iabdelha-AF3-workspace/MassiveFold/massivefold_runs/output/H1140/af3_default_run/af3_batch_.json
  --db_dir /data/horse/ws/iabdelha-AF3-workspace/Alphafold3-2024-12
  --model_dir /data/horse/ws/iabdelha-AF3-workspace/Alphafold3-2024-12
  --output_dir /data/horse/ws/iabdelha-AF3-workspace/MassiveFold/massivefold_runs/output/H1140/af3_default_run/
  --jackhmmer_binary_path /home/iabdelha/.conda/envs/mf-alphafold3/bin/jackhmmer
  --hmmalign_binary_path /home/iabdelha/.conda/envs/mf-alphafold3/bin/hmmalign
  --hmmbuild_binary_path /home/iabdelha/.conda/envs/mf-alphafold3/bin/hmmbuild
  --hmmsearch_binary_path /home/iabdelha/.conda/envs/mf-alphafold3/bin/hmmsearch
Traceback (most recent call last):
  File "/home/iabdelha/.conda/envs/mf-alphafold3/bin/run_alphafold.py", line 735, in <module>
    app.run(main)
  File "/home/iabdelha/.conda/envs/mf-alphafold3/lib/python3.12/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/iabdelha/.conda/envs/mf-alphafold3/lib/python3.12/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/iabdelha/.conda/envs/mf-alphafold3/bin/run_alphafold.py", line 623, in main
    fold_inputs = folding_input.load_fold_inputs_from_path(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iabdelha/.conda/envs/mf-alphafold3/lib/python3.12/site-packages/alphafold3/common/folding_input.py", line 1018, in load_fold_inputs_from_path
    with open(json_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/horse/ws/iabdelha-AF3-workspace/MassiveFold/massivefold_runs/output/H1140/af3_default_run/af3_batch_.json'

real	1m10.565s
user	0m2.358s
sys	0m1.597s
Fri Dec 13 08:18:46 PM CET 2024

Can you help me solve this issue? Thank you in advance for your help

Sincerely,
Ilyes

**Comment by IlyesAbdelhamid** [comment]
The issue was resolved by adding the following line to the job array's job file header:

#SBATCH --array=0-$substitute_batch_number
With this fix, I successfully ran the H1140.fasta example file on my cluster.

Timings Recorded:
Alignment (from alignment log file):
real: 32m34.417s
user: 110m7.870s
sys: 12m48.820s

Inference (from job array log file):
real: 11m0.652s
user: 1m2.120s
sys: 0m12.370s
Comparison with the AlphaFold Server:
The AlphaFold server completed the same simulation in approximately 2 minutes, a significant difference in speed compared to my cluster setup.

Question:
What could explain such a performance gap, and how can I optimize my cluster's configuration and MassiveFold parameters to approach the AlphaFold server's speed?

My Cluster Configuration:
144 nodes, each with:
4 x NVIDIA H100-SXM5 Tensor Core GPUs (94 GB HBM2e per GPU)
2 x AMD EPYC 9334 CPUs (32 cores @ 2.7 GHz, multithreading disabled)
768 GB RAM (12 x 32 GB DDR5-4800 MT/s per socket)
800 GB local storage on NVMe at /tmp.


Sincerely,
Ilyes

**Comment by IlyesAbdelhamid** [comment]
Dear Nessim,

Thank you for your reply. Actually I only need -p 1
So if I put :  ./run_massivefold.sh -s input/H1140.fasta -r af3_default_run
-p 1 -b 2 -f AlphaFold3_params.json -t AlphaFold3
Should I also change the following information in my jobarray.slurm:
#SBATCH --gres=gpu:1 and put 4 (as I have access to 4 H100 in a node) ?


Sincerely,
Ilyes

Le lun. 16 déc. 2024 à 20:00, Nessim Raouraoua ***@***.***> a
écrit :

**Comment by NessimRaou** [comment]
Ilyes,

Actually, if you only have `-p 1`, you cannot parallelize it so `-b` won't have incidence. For `#SBATCH --gres=gpu:1`, you should always keep it that way, the jobarray manages the parallelization by sending one job per batch, each job running on a single GPU, AlphaFold3 does not support multi-GPU usage for a single run.

Normally, `-p 1` will be fast enough for you, the other parameters are to accommodate massive sampling (high number of  predictions). Also, I read it wrong, if you have more than 5 GPU (which you have with 144 nods), you could do `-b 1` with `-p 5` (or more).

Regards,
Nessim

**Comment by IlyesAbdelhamid** [comment]
Dear Nessim,

Indeed I only need -p 1 just like the output of the AF server.
Thanks.

Sincerely,
Ilyes

Le lun. 16 déc. 2024 à 20:59, Nessim Raouraoua ***@***.***> a
écrit :
